### PR TITLE
Staging

### PR DESCRIPTION
**Pull request by jmgreg31**

### CODE REVIEW

**Comment by jmgreg31** [comment]
@schammah lgtm.  For furture reference the bump version script will handle the update to the changelog as long as it's listed as `UNRELEASED`

**Comment by schammah** [comment]
@jmgreg31 right, you're correct, forgot that
always doing that as mentioned in Contribute but went too fast this time

**Comment by jmgreg31** [comment]
@schammah yup no problem, it doesn't impact current PR.  If no other changes, I can merge

**Comment by schammah** [comment]
@jmgreg31 fine with me, you can merge, not adding anything else for now

**Pull request merged**
