### PR TITLE
Eyalmor/fix_custom_headers_dynamic_s3

### PR DESCRIPTION
**Pull request by eyalmor94**
Add the ability to specify custom headers in the `dynamic_s3_origin_config` variable.
The fix mimics the functionality and implementation of `dynamic_custom_origin_config` variable.

IDE auto removed redundant white spaces.

### CODE REVIEW

**Comment by eyalmor94** [comment]
Hi @jmgreg31!

I work with @schammah and we have found a bug in the current implementation of the dynamic_s3_origin_config when setting custom headers.

Can you please review at your convenience 😄

**Comment by jmgreg31** [comment]
@eyalmor94 thanks for the updates.  Can you please update the `VERSION` file to `4.3.2`

**Comment by eyalmor94** [comment]
@jmgreg31 Updated 😄

**Comment by jmgreg31** [comment]
lgtm

**Pull request merged**
