### PR TITLE
Add support for response headers policy use

### PR DESCRIPTION
**Pull request by slonokot**
Add support for [response headers policies](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/using-managed-response-headers-policies.html) use. 
In cases when Security headers, CORS or custom headers are need to be added to the response headers one is forced to have to add a proxy or Lambda@edge origin response function to add the headers. This feature **removes** the requirement.

### CODE REVIEW

**Comment by slonokot** [comment]
Hi @jmgreg31, hope you're still watching this repo (it lacks any activity from 2021). I tried to add the feature and the CI fails on `Error: error configuring S3 Backend: no valid credential sources for S3 Backend found.` Can I ask you to help me figuring this out?

**Comment by jmgreg31** [comment]
Hey @slonokot thanks for the PR!  To be honest, once the supported module was released, I hadn’t spent much time keeping this module up to date with the latest since it is very similar in implementation.  https://github.com/terraform-aws-modules/terraform-aws-cloudfront

Looks like the acct creds expired where the integration tests were running and will take a closer look into it.

**Comment by slonokot** [comment]
@jmgreg31  Thank you for looking into it!

Yes, I evaluated moving to that module - it would require quite an investment at this point due to different API.

**Comment by jmgreg31** [comment]
@slonokot Can you rebase and push.  Spent time today working on migrating from Travis to native GitHub Actions and believe this should be resolved now.  Apologies in advance for the git history since I had to actively test being the first time looking into actions specifically

**Comment by jmgreg31** [comment]
@slonokot tried to review the docs of reusable workflows from forks as I think that's the issue with passing secrets and why the run was failing on your commits.  I think changing to the default `GITHUB_TOKEN `instead of the one I configured for the environment should work (and is why it worked from a PR of local branch instead of a fork).  As a sanity check, I created a quick PR with the action updates and the changes you provided.  https://github.com/jmgreg31/terraform-aws-cloudfront/pull/49

If you can resolve the `staging.yml` workflow conflict, I am hoping that will resolve the issue.

**Comment by jmgreg31** [comment]
@slonokot Appreciate the patience, I still am having trouble passing the AWS Creds to the Environment.  I'll have to take a closer look at it later, but don't want to hold this up for you any longer.  Changes are merged and released `v4.3.6`.  Thanks again!

**Comment by slonokot** [comment]
@jmgreg31 very much appreciated! If every repository owner was that kind 😄

**Pull request merged**
