### PR TITLE
Cloudfront Outputs

### PR DESCRIPTION
**Pull request by adaranutsa**
Adding all available Cloudfront outputs
Leaving "name" output for backwards compatibility

### CODE REVIEW

**Comment by jmgreg31** [comment]
@adaranutsa Overall looks great.  Would you mind adding an entry to the the CHANGELOG as well?

**Comment by adaranutsa** [comment]
@jmgreg31 Do you want me to add the entries under a new version?

**Comment by jmgreg31** [comment]
@adaranutsa  That be great.  release `4.1.0`

**Comment by jmgreg31** [comment]
lgtm :rocket:

**Pull request merged**
