### PR TITLE
Update `versions.tf` to Enable AWS Provider 4.x.x

### PR DESCRIPTION
**Pull request by eyalle**
Enable upgrading AWS provider version to 4.x.x

### CODE REVIEW

**Comment by eyalle** [comment]
Hi @jmgreg31 

We use your module, and would like to be able to work with AWS provider 4.x.x & above.
Can you add a release adding this capability? Is there anything I should add to the PR?
Apologies if I missed anything 🙏

**Review by jmgreg31 — APPROVED** [review]
@eyalle typically, the process flow is to submit the PR to the staging branch so the CI would trigger.  Since this is an optional version bump that is backwards compatible, and havent had the time to refine the CI since switching to GitHub actions, this LGTM.  I'll go ahead and bump the version

**Comment by eyalle** [comment]
thanks @jmgreg31 , sorry for the broken process on my end 😅 

I've also updated the VERSION file as suggested 🙏

**Comment by jmgreg31** [comment]
@eyalle manually released `v4.3.7` .  I’ll have to work on fixing the CI when I get a chance.  Thanks for providing the updates!

**Comment by eyalle** [comment]
> @eyalle manually released `v4.3.7` . I’ll have to work on fixing the CI when I get a chance. Thanks for providing the updates!

Thank you! 🙏

**Pull request merged**
