### PR TITLE
Staging

### PR DESCRIPTION
**Pull request by jmgreg31**
Testing @schammah changes

### CODE REVIEW

**Comment by jmgreg31** [comment]
@schammah this build is passing.  If you don't have any additional changes in mind for this release, I can merge.

One additional question.  If the new proposed syntax is working to iterate through the cache behaviors, why not update for the origins, origin groups, member blocks...etc?  Is there a reason you left those, i.e. certain conditions where the more involved iterator is needed?

example of legacy format in origin block:
```hcl
dynamic "origin" {
    for_each = [for i in var.dynamic_s3_origin_config : {
      name          = i.domain_name
      id            = i.origin_id
      identity      = lookup(i, "origin_access_identity", null)
      path          = lookup(i, "origin_path", null)
      custom_header = lookup(i, "custom_header", null)
    }]
```

**Comment by schammah** [comment]
yes i know, few things before we merge
- only reason i didn't do the new syntax for everything yet is I didn't have really much time , did the PR till 3am and need to use this module to implement some new environments, as soon i find time we will do it
- i would like to test the outputs, my change my have broken the syntax, so will test to make sure its backward compatible (if you can test as well let me know)
- waiting for your answer about the `provider.tf` do we really need it? i added `versions.tf` and provider is more something you want to include in your implementation, should i `git rm` it?

**Comment by jmgreg31** [comment]
@schammah sorry, wasn't clear to me what you were asking about the `provider.tf` but I follow now.  I removed it from the module.  I added the provider as well `create_cf` in the example

**Comment by schammah** [comment]
i think `terraform output` will result empty unless you apply

**Comment by schammah** [comment]
before we merge wanna add a few more commits please
any chance i get rights to push to `staging` branch?

**Comment by jmgreg31** [comment]
> i think `terraform output` will result empty unless you apply

You're right

> before we merge wanna add a few more commits please
> any chance i get rights to push to `staging` branch?

The pattern I'd prefer to follow is submitting a PR to the staging branch instead of giving users access to push directly

**Comment by jmgreg31** [comment]
@schammah Thanks for the work on this PR and appreciate you working through some of the CI processes.  

I added `additional_tags` and all the outputs to the example for more complete testing in the future.  Merging this.

**Pull request merged**
