### PR TITLE
Staging

### PR DESCRIPTION
**Pull request by jmgreg31**

### CODE REVIEW

**Comment by jmgreg31** [comment]
@schammah here is the error output 
```
on main.tf line 165, in output "active_trusted_signers":
 165:   value       = module.demo_cf.active_trusted_signers
An output value with the name "active_trusted_signers" has not been declared
in module.demo_cf.
```
Think it just needs to be modified to `trusted_signers`

In addition, the travis.yml file should be updated to tf version 13 for valid testing.  I'm not sure i'll get a chance to modify this today, so if you'd like to submit another PR to staging I'll merge and re-run

**Comment by jmgreg31** [comment]
@schammah nvmd, had some extra time this morning - this lgtm. If the additional small changes look good to you as well I can merge this in.

**Comment by schammah** [comment]
i see now
for testing it wasnt a must to test with 0.13 , this upgrade the provider but still works under both 0.12 & 0.13

**Comment by jmgreg31** [comment]
haha, a future release for sure re: trusted_signers.

**Pull request merged**
